### ISSUE TITLE
Setup Website

### ISSUE THREAD

**Issue by nate-double-u** [containernetworking/cni.dev#59]
The https://www.cni.dev website is at a point where I can hand it off to the [CNI](https://github.com/containernetworking) community. (There's already a PR in from the community for docs updates).

I'm happy to continue to help out and provide support and advice in future.

There are a couple issues still in the backlog of the [cni.dev website setup project](https://github.com/containernetworking/cni.dev/projects/2), but they are outside the scope of setup. I'll archive that project, create a new one for ongoing work and maintenance, and will add those issues to it.

I'm opening this issue as per @caniszczyk's suggestion. Please sign off if you agree that the setup phase is over—or by all means, if you think the site is not yet ready, please let us know!

@squeed, @bboreham, @dcbw, @mccv1r0 
CC @zacharysarah, @caniszczyk

**Comment by bboreham** [comment]
Thanks Nate!  Looks great.

**Comment by nate-double-u** [comment]
Thanks everyone! I'll be around if you've got any questions or want help with anything.
