### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by bduffany** [containernetworking/cni.dev#78]
I keep getting a bunch of 503s from cni.dev.

**Comment by bduffany** [comment]
Might be a problem with my network. Closing

**Comment by nate-double-u** [comment]
Thanks for flagging this. Looks like some other folks also got the 503 briefly, so I'll see what I can see in the Netlify logs. Things seem to be up now, so I'll leave this closed unless I find something.

**Comment by nate-double-u** [comment]
I didn't find anything in the site specific logs, but Netlify was having some increased latency issues during the time frame that we were seeing issues.

https://www.netlifystatus.com/incidents/j3mhkz4gy2cv
https://www.netlifystatus.com/incidents/vl59d9dw7p68
